"""Integration tests for ApochCoordinator.recommend() with REAL components.

Uses:
  - REAL OracleModule (from apoch.modules.oracle.module)
  - REAL RecommendationEngine (from apoch.modules.oracle.engine)
  - REAL GuardianModule (from apoch.modules.guardian.module)
  - REAL Module/Context from apoch.core.module
  - REAL OptimizationHypothesis from apoch.modules.optimizer.models

Minimal fakes:
  - VisionStub (VisionModule requires full engine to be running)
  - Hypotheses injection λ (OptimizerModule requires Pulse + real data)

No Oracle or Guardian methods are mocked.  Every Recommendation object
is generated by the real RecommendationEngine from real hypotheses.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest

from apoch.core.module import Context, Module, ModuleState
from apoch.modules.guardian.diagnostics import ModuleDiagnostics
from apoch.modules.guardian.module import GuardianModule
from apoch.modules.optimizer.models import OptimizationHypothesis
from apoch.modules.oracle.module import OracleModule
from apoch.public_api.coordinator import ApochCoordinator
from apoch.public_api.registry import ServiceRegistry

# ---------------------------------------------------------------------------
# Test doubles (minimal — only where real modules can't run)
# ---------------------------------------------------------------------------


class _HealthyModule(Module):
    """Minimal module whose start() succeeds normally."""

    def __init__(self) -> None:
        super().__init__({})

    async def start(self, context: Context) -> None:
        pass

    async def stop(self) -> None:
        pass

    async def shutdown(self) -> None:
        pass


class _FailingModule(Module):
    """Module whose start() raises RuntimeError — triggers Guardian.protect()."""

    def __init__(self, name: str = "_FailingModule") -> None:
        super().__init__({})
        self._module_name = name

    async def start(self, context: Context) -> None:
        msg = "simulated start failure"
        raise RuntimeError(msg)

    async def stop(self) -> None:
        pass

    async def shutdown(self) -> None:
        pass


class _FailingAlpha(Module):
    """Separate class so Guardian._diagnostics has a distinct key."""

    def __init__(self) -> None:
        super().__init__({})

    async def start(self, context: Context) -> None:
        raise RuntimeError("alpha failure")

    async def stop(self) -> None:
        pass

    async def shutdown(self) -> None:
        pass


class _FailingBeta(Module):
    """Separate class so Guardian._diagnostics has a distinct key."""

    def __init__(self) -> None:
        super().__init__({})

    async def start(self, context: Context) -> None:
        raise RuntimeError("beta failure")

    async def stop(self) -> None:
        pass

    async def shutdown(self) -> None:
        pass


class _VisionStub:
    """Minimal Vision stub — real VisionModule needs a running Engine."""

    async def module_state(self) -> dict:
        return {"state": "running", "modules": 0}


# ---------------------------------------------------------------------------
# Test hypothesis
# ---------------------------------------------------------------------------

_REAL_HYPOTHESIS = OptimizationHypothesis(
    type="anomaly",
    domain="cost",
    confidence=0.95,
    evidence={"metric": "token_cost_per_task", "value": 42.5, "threshold": 10.0},
    affected_scope="cost domain token usage",
    generated_at=datetime.now(UTC).isoformat(),
)

_REAL_HYPOTHESIS_2 = OptimizationHypothesis(
    type="pattern",
    domain="session_behavior",
    confidence=0.65,
    evidence={"metric": "session_duration_avg", "value": 320, "trend": "increasing"},
    affected_scope="session behavior domain",
    generated_at=datetime.now(UTC).isoformat(),
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def ctx() -> Context:
    return Context()


@pytest.fixture
async def real_oracle_with_hypotheses() -> OracleModule:
    """Return a started OracleModule seeded with real hypotheses.

    The ``optimizer.hypotheses`` context service is a lambda (no real
    Optimizer module), but the OracleModule and RecommendationEngine are
    100% real — all Recommendation objects are generated by real logic.
    """
    oracle = OracleModule({})
    context = Context()
    context.services["optimizer.hypotheses"] = lambda: [_REAL_HYPOTHESIS]
    await oracle.start(context)
    yield oracle
    await oracle.stop()
    await oracle.shutdown()


@pytest.fixture
async def real_oracle_with_multiple_hypotheses() -> OracleModule:
    """OracleModule seeded with two hypotheses for priority tests."""
    oracle = OracleModule({})
    context = Context()
    context.services["optimizer.hypotheses"] = lambda: [
        _REAL_HYPOTHESIS,  # cost/anomaly → critical
        _REAL_HYPOTHESIS_2,  # session_behavior/pattern → low
    ]
    await oracle.start(context)
    yield oracle
    await oracle.stop()
    await oracle.shutdown()


@pytest.fixture
async def real_guardian_with_failure(ctx: Context) -> GuardianModule:
    """GuardianModule with one captured RuntimeError from _FailingModule."""
    guardian = GuardianModule({})
    failing = _FailingModule()
    await guardian.protect(failing.start(ctx), failing)
    yield guardian


@pytest.fixture
async def real_guardian_with_alpha_beta(ctx: Context) -> GuardianModule:
    """GuardianModule with two distinct failures."""
    guardian = GuardianModule({})
    alpha = _FailingAlpha()
    beta = _FailingBeta()
    await guardian.protect(alpha.start(ctx), alpha)
    await guardian.protect(beta.start(ctx), beta)
    yield guardian


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestRecommendWithRealOracle:
    """Real OracleModule + real RecommendationEngine generating real Recs."""

    async def test_recommend_clean_system(
        self,
        real_oracle_with_hypotheses: OracleModule,
    ) -> None:
        """Real Oracle, no Guardian failures → recommendation from engine, not 'No hay'."""
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # The engine generates real Recommendation from cost/anomaly hypothesis
        assert result["summary"] == "Cost anomaly detected"
        assert (
            "Based on Anomaly analysis in Cost domain with 95% confidence" in result["explanation"]
        )
        # cost/anomaly → critical → "HIGH"
        assert result["priority"] == "HIGH"
        # base confidence 0.9 (from _PRIORITY_MAP cost/anomaly)
        assert result["confidence"] == 0.9
        assert result["suggested_action"] is None

        # Evidence: only "Sistema de recomendaciones" (Oracle), no Guardian/Vision
        assert len(result["evidence"]) == 1
        assert result["evidence"][0]["source"] == "Sistema de recomendaciones"

    async def test_recommend_state_change(
        self,
        real_oracle_with_hypotheses: OracleModule,
        ctx: Context,
    ) -> None:
        """Clear and re-add failures → recommendation changes accordingly."""
        guardian = GuardianModule({})
        failing = _FailingModule()
        await guardian.protect(failing.start(ctx), failing)

        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses
        registry.guardian = guardian

        coordinator = ApochCoordinator(registry)

        # Oracle has priority over fallback — so Oracle rec is used even with failures
        result = await coordinator.recommend()
        assert result["summary"] == "Cost anomaly detected"

        # Now clear Oracle's hypotheses — Oracle returns [] → fallback to Guardian
        # We need a fresh Oracle with no hypotheses
        oracle_empty = OracleModule({})
        context = Context()
        context.services["optimizer.hypotheses"] = lambda: []  # no hypotheses
        await oracle_empty.start(context)

        registry2 = ServiceRegistry()
        registry2.oracle = oracle_empty
        registry2.guardian = guardian
        coordinator2 = ApochCoordinator(registry2)

        result2 = await coordinator2.recommend()
        assert "_FailingModule" in result2["summary"]
        assert result2["priority"] == "HIGH"  # ERROR from FAILED

        # Clear diagnostics → recommendation reverts to "No hay"
        guardian.clear_all_diagnostics()

        result3 = await coordinator2.recommend()
        assert result3["summary"] == "No hay recomendaciones en este momento."
        assert result3["priority"] == "LOW"

        await oracle_empty.stop()
        await oracle_empty.shutdown()

    async def test_recommend_multiple_hypotheses_uses_first(
        self,
        real_oracle_with_multiple_hypotheses: OracleModule,
    ) -> None:
        """Multiple recs → coordinator uses first (highest priority)."""
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_multiple_hypotheses

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # First rec is cost/anomaly → critical ("HIGH"), not session_behavior/pattern
        assert result["summary"] == "Cost anomaly detected"
        assert result["priority"] == "HIGH"

    async def test_recommend_response_contract(
        self,
        real_oracle_with_hypotheses: OracleModule,
    ) -> None:
        """Full ToolResponse + RecommendResponse contract verification."""
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # ToolResponse base fields
        assert result["api_version"] == "1.0"
        assert isinstance(result["summary"], str)
        assert result["summary"]
        assert isinstance(result["explanation"], str)
        assert result["explanation"]
        assert isinstance(result["confidence"], float)
        assert 0.0 <= result["confidence"] <= 1.0
        assert isinstance(result["evidence"], list)
        assert result["suggested_action"] is None
        assert isinstance(result["generated_at"], str)
        assert isinstance(result["data_freshness"], int)
        assert isinstance(result["metadata"], dict)

        # RecommendResponse fields
        assert isinstance(result["priority"], str)
        assert result["priority"] in ("LOW", "MEDIUM", "HIGH", "CRITICAL")

        # No fields from other tools
        assert "diagnostics" not in result
        assert "events" not in result
        assert "productivity" not in result


class TestRecommendOracleWithGuardian:
    """Real Oracle + real Guardian — Oracle's engine applies health degradation."""

    async def test_recommend_failed_module(
        self,
        real_oracle_with_hypotheses: OracleModule,
        real_guardian_with_failure: GuardianModule,
    ) -> None:
        """Real Oracle + real Guardian failure → Oracle rec still wins (CASE 1).

        The coordinator always uses Oracle rec[0] when available. Guardian
        failure only affects evidence, NOT the recommendation content.
        """
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses
        registry.guardian = real_guardian_with_failure
        registry.vision = _VisionStub()

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # Oracle rec still used (CASE 1 takes priority)
        assert result["summary"] == "Cost anomaly detected"
        assert result["priority"] == "HIGH"

        # Guardian failure appears in evidence
        guardian_evidence = [
            e for e in result["evidence"] if e["source"] == "Diagnóstico del sistema"
        ]
        assert len(guardian_evidence) == 1
        assert "1 problema(s)" in guardian_evidence[0]["based_on"]

        # All three evidence sources present
        sources = {e["source"] for e in result["evidence"]}
        assert sources == {
            "Sistema de recomendaciones",
            "Diagnóstico del sistema",
            "Estado de componentes",
        }

    async def test_recommend_confidence_with_oracle(
        self,
        real_oracle_with_hypotheses: OracleModule,
    ) -> None:
        """Confidence comes from the real Recommendation (cost/anomaly → 0.9)."""
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # Base confidence from _PRIORITY_MAP: cost/anomaly → 0.9
        assert result["confidence"] == 0.9


class TestRecommendFallbackWithRealGuardian:
    """Fallback path (no Oracle / Oracle empty) with real Guardian failures."""

    async def test_recommend_fallback_failed_module(
        self,
        real_guardian_with_failure: GuardianModule,
    ) -> None:
        """No Oracle + Guardian FAILED → fallback generates recommendation."""
        registry = ServiceRegistry()
        registry.guardian = real_guardian_with_failure

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # Fallback picks the worst problem
        assert "_FailingModule" in result["summary"]
        assert result["priority"] == "HIGH"  # ERROR → HIGH
        assert result["confidence"] == 0.5  # fallback confidence
        assert result["suggested_action"] is None
        assert "[ERROR]" in result["explanation"]

    async def test_recommend_fallback_warning_only(self) -> None:
        """Guardian has non-FAILED diagnostic with last_error → WARNING severity.

        GuardianModule.protect() always produces FAILED state.  To get a
        WARNING-level diagnostic we inject a ModuleDiagnostics with
        RUNNING state but last_error set (simulates a degraded module).
        """
        guardian = GuardianModule({})
        guardian._diagnostics["pulse"] = ModuleDiagnostics(
            module_name="pulse",
            current_state=ModuleState.RUNNING.value,
            last_error="High latency detected",
            last_error_traceback=None,
            fail_count=0,
            last_failure_time=None,
        )

        registry = ServiceRegistry()
        registry.guardian = guardian

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # WARNING → MEDIUM priority
        assert "pulse" in result["summary"]
        assert result["priority"] == "MEDIUM"
        assert result["confidence"] == 0.5
        assert "[WARNING]" in result["explanation"]

    async def test_recommend_multiple_failures_prioritizes_worst(
        self,
        real_guardian_with_alpha_beta: GuardianModule,
    ) -> None:
        """Two FAILED modules → both ERROR → first sorted is reported."""
        # Inject a WARNING alongside the two FAILED modules to test ordering
        real_guardian_with_alpha_beta._diagnostics["pulse"] = ModuleDiagnostics(
            module_name="pulse",
            current_state=ModuleState.RUNNING.value,
            last_error="High latency",
            last_error_traceback=None,
            fail_count=0,
            last_failure_time=None,
        )

        registry = ServiceRegistry()
        registry.guardian = real_guardian_with_alpha_beta

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        # ERROR severity has order 0, WARNING has order 1 → ERROR is reported
        assert result["priority"] == "HIGH"
        assert "[ERROR]" in result["explanation"]

        # At least one failing module name is in the summary
        names_in_summary = any(
            name in result["summary"] for name in ("_FailingAlpha", "_FailingBeta")
        )
        assert names_in_summary, (
            f"Neither _FailingAlpha nor _FailingBeta in summary: {result['summary']}"
        )

    async def test_recommend_fallback_idempotent(
        self,
        real_guardian_with_failure: GuardianModule,
    ) -> None:
        """Same state → same response across calls."""
        registry = ServiceRegistry()
        registry.guardian = real_guardian_with_failure

        coordinator = ApochCoordinator(registry)

        r1 = await coordinator.recommend()
        r2 = await coordinator.recommend()

        assert r1["summary"] == r2["summary"]
        assert r1["explanation"] == r2["explanation"]
        assert r1["confidence"] == r2["confidence"]
        assert r1["priority"] == r2["priority"]

    async def test_recommend_confidence_with_fallback(
        self,
        real_guardian_with_failure: GuardianModule,
    ) -> None:
        """Fallback with Guardian failure → confidence = 0.5."""
        registry = ServiceRegistry()
        registry.guardian = real_guardian_with_failure

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        assert result["confidence"] == 0.5

    async def test_recommend_fallback_healthy(self) -> None:
        """No Oracle, no Guardian failures → 'No hay recomendaciones', confidence 1.0."""
        registry = ServiceRegistry()
        registry.guardian = GuardianModule({})
        registry.vision = _VisionStub()

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        assert result["summary"] == "No hay recomendaciones en este momento."
        assert result["priority"] == "LOW"
        assert result["confidence"] == 1.0
        assert result["suggested_action"] is None


class TestRecommendEvidenceWithRealComponents:
    """Evidence varies with available sources — not static."""

    async def test_recommend_evidence_oracle_only(
        self,
        real_oracle_with_hypotheses: OracleModule,
    ) -> None:
        """Only Oracle registered → evidence has single entry."""
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        sources = {e["source"] for e in result["evidence"]}
        assert sources == {"Sistema de recomendaciones"}

    async def test_recommend_evidence_oracle_and_guardian(
        self,
        real_oracle_with_hypotheses: OracleModule,
        real_guardian_with_failure: GuardianModule,
    ) -> None:
        """Oracle + Guardian (no Vision) → two evidence entries."""
        registry = ServiceRegistry()
        registry.oracle = real_oracle_with_hypotheses
        registry.guardian = real_guardian_with_failure
        # No vision

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        sources = {e["source"] for e in result["evidence"]}
        assert sources == {"Sistema de recomendaciones", "Diagnóstico del sistema"}

    async def test_recommend_evidence_fallback_guardian_only(self) -> None:
        """Fallback with only Guardian → one evidence entry."""
        guardian = GuardianModule({})

        # Inject a diagnostic for fallback to have something to report
        guardian._diagnostics["some_module"] = ModuleDiagnostics(
            module_name="some_module",
            current_state=ModuleState.FAILED.value,
            last_error="Something broke",
            last_error_traceback=None,
            fail_count=1,
            last_failure_time=datetime.now(UTC).isoformat(),
        )

        registry = ServiceRegistry()
        registry.guardian = guardian

        coordinator = ApochCoordinator(registry)
        result = await coordinator.recommend()

        sources = {e["source"] for e in result["evidence"]}
        # Only "Diagnóstico del sistema" — no Oracle, no Vision
        assert sources == {"Diagnóstico del sistema"}
