"""Integration tests for ApochCoordinator.insights() with REAL components.

Uses:
  - REAL OptimizerModule (from apoch.modules.optimizer.module)
  - REAL PulseModule (from apoch.modules.pulse.module)
  - REAL PulseStore (from apoch.modules.pulse.storage) — in-memory dict backend
  - REAL WorkUnit, MeasurementInput (from apoch.modules.pulse.models)
  - REAL OptimizationHypothesis (from apoch.modules.optimizer.models)
  - REAL 6 detectors: BaselineGenerator, DegradationDetector, etc.
  - REAL Module/Context from apoch.core.module

Minimal fakes:
  - None for Pulse — PulseModule runs fully real with in-memory PulseStore.
  - None for Optimizer — OptimizerModule runs fully real with 6 real detectors.
  - No mocked methods on PulseModule or OptimizerModule at all.

Every Optimizer hypothesis is generated by REAL detectors from REAL WorkUnits.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

import pytest

from apoch.core.module import Context
from apoch.modules.optimizer.module import OptimizerModule
from apoch.modules.pulse.models import MeasurementInput
from apoch.modules.pulse.module import PulseModule
from apoch.public_api.coordinator import ApochCoordinator
from apoch.public_api.registry import ServiceRegistry

# ---------------------------------------------------------------------------
# Fixtures: REAL PulseModule + REAL OptimizerModule
# ---------------------------------------------------------------------------


@pytest.fixture
def empty_context() -> Context:
    """Empty Context — no cross-module services."""
    return Context()


@pytest.fixture
def real_pulse(empty_context: Context) -> PulseModule:
    """A REAL PulseModule with in-memory PulseStore, started and ready."""
    import asyncio

    mod = PulseModule({})
    asyncio.run(mod.start(empty_context))
    return mod


def _seed_work_unit(
    pulse: PulseModule,
    *,
    id: str | None = None,
    model: str = "gpt-4",
    tokens_input: int = 100,
    tokens_output: int = 50,
    wall_clock_s: float = 10.0,
    cost: Decimal | None = Decimal("0.01"),
    hours_ago: int = 1,
    created_at: str | None = None,
) -> None:
    """Seed one WorkUnit into *pulse* via REAL record().

    Overwrites created_at when explicitly provided for deterministic
    trend/temporal testing.
    """
    final_id = id or f"ins-wu-{hours_ago}-{tokens_input}"
    inp = MeasurementInput(
        session_id="insights-integration",
        work_unit_id=final_id,
        model=model,
        tokens_input=tokens_input,
        tokens_output=tokens_output,
        wall_clock_s=wall_clock_s,
        cost=cost,
        lines_original=10,
        lines_modified=2,
    )
    unit = pulse.record(inp)
    if created_at is not None:
        object.__setattr__(unit, "created_at", created_at)


def _seed_multiple(pulse: PulseModule, units: list[dict]) -> None:
    """Seed multiple WorkUnits, each defined by a dict.

    Dict keys: id, model, tokens_input, tokens_output, wall_clock_s,
               cost, hours_ago, created_at.
    """
    for kwargs in units:
        _seed_work_unit(pulse, **kwargs)


@pytest.fixture
def pulse_with_data(real_pulse: PulseModule) -> PulseModule:
    """PulseModule with 5 seeded WorkUnits across different models/times."""
    now = datetime.now(UTC)
    _seed_multiple(
        real_pulse,
        [
            {
                "id": "ins-wu-baseline-1",
                "model": "gpt-4",
                "tokens_input": 100,
                "tokens_output": 50,
                "cost": Decimal("0.01"),
                "created_at": (now - timedelta(hours=4)).isoformat(),
            },
            {
                "id": "ins-wu-baseline-2",
                "model": "gpt-4",
                "tokens_input": 120,
                "tokens_output": 60,
                "cost": Decimal("0.012"),
                "created_at": (now - timedelta(hours=3)).isoformat(),
            },
            {
                "id": "ins-wu-baseline-3",
                "model": "gpt-4",
                "tokens_input": 90,
                "tokens_output": 45,
                "cost": Decimal("0.009"),
                "created_at": (now - timedelta(hours=2)).isoformat(),
            },
            {
                "id": "ins-wu-baseline-4",
                "model": "gpt-4",
                "tokens_input": 110,
                "tokens_output": 55,
                "cost": Decimal("0.011"),
                "created_at": (now - timedelta(hours=1)).isoformat(),
            },
            {
                "id": "ins-wu-baseline-5",
                "model": "gpt-4",
                "tokens_input": 130,
                "tokens_output": 65,
                "cost": Decimal("0.013"),
                "created_at": now.isoformat(),
            },
        ],
    )
    return real_pulse


@pytest.fixture
def optimizer_with_pulse(pulse_with_data: PulseModule) -> OptimizerModule:
    """REAL OptimizerModule connected to REAL PulseModule via Context."""
    ctx = Context(services={"pulse.measurements": pulse_with_data.list})
    mod = OptimizerModule({})
    import asyncio

    asyncio.run(mod.start(ctx))
    return mod


@pytest.fixture
def optimizer_no_pulse() -> OptimizerModule:
    """REAL OptimizerModule with no Pulse connected."""
    ctx = Context()  # no pulse.measurements
    mod = OptimizerModule({})
    import asyncio

    asyncio.run(mod.start(ctx))
    return mod


@pytest.fixture
def full_registry(
    optimizer_with_pulse: OptimizerModule, pulse_with_data: PulseModule
) -> ServiceRegistry:
    """Registry with REAL Optimizer + REAL Pulse."""
    return ServiceRegistry(optimizer=optimizer_with_pulse, pulse=pulse_with_data)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestInsightsIntegrationHappyPath:
    """REAL Optimizer with REAL data — full pipeline verification."""

    async def test_summary_includes_pattern_count(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Real detectors produce at least one pattern → summary mentions count."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        assert "error" not in result
        assert "patrones" in result["summary"] or "patrón" in result["summary"]
        assert result["suggested_action"] is None
        assert result["api_version"] == "1.0"

    async def test_explanation_uses_natural_language(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Explanation uses 'Detecté un patrón' format."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        assert "Detecté un patrón en" in result["explanation"]

    async def test_response_contract(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """All ToolResponse fields present — no internal leaks."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        assert set(result.keys()) == {
            "api_version",
            "summary",
            "explanation",
            "evidence",
            "suggested_action",
            "confidence",
            "generated_at",
            "data_freshness",
            "metadata",
        }
        # P6: no internal structure leaks
        assert result["metadata"] == {}
        assert result["data_freshness"] == 0
        assert result["suggested_action"] is None

    async def test_evidence_has_optimizer_source(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Evidence includes 'Sistema de optimización'."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        sources = [e["source"] for e in result["evidence"]]
        assert "Sistema de optimización" in sources

    async def test_evidence_includes_pulse_when_available(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Pulse available → evidence includes 'Sistema de rendimiento'."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        sources = [e["source"] for e in result["evidence"]]
        assert "Sistema de rendimiento" in sources

    async def test_evidence_no_internal_data(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Evidence entries NEVER expose internal stats, mean, std, tokens."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        for entry in result["evidence"]:
            assert "mean" not in entry
            assert "std" not in entry
            assert "tokens" not in entry
            assert "cost" not in entry
            assert "model" not in entry
            assert isinstance(entry["source"], str)
            assert isinstance(entry["confidence"], (int, float))
            assert "based_on" in entry

    async def test_confidence_is_within_range(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Confidence is between 0.0 and 1.0."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        assert 0.0 <= result["confidence"] <= 1.0

    async def test_generated_at_is_iso(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """generated_at is parseable ISO 8601."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        dt = datetime.fromisoformat(result["generated_at"])
        assert dt.tzinfo is not None

    async def test_idempotent_call(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Consecutive calls return same structure (diff generated_at)."""
        coordinator = ApochCoordinator(full_registry)
        r1 = await coordinator.insights()
        r2 = await coordinator.insights()

        assert r1["summary"] == r2["summary"]
        assert len(r1["evidence"]) == len(r2["evidence"])
        assert r1["confidence"] == r2["confidence"]
        # generated_at differs
        assert r1["generated_at"] != r2["generated_at"]


class TestInsightsIntegrationNoPatterns:
    """Optimizer runs but produces no type='pattern' hypotheses."""

    async def test_only_anomalies_no_patterns(
        self,
        real_pulse: PulseModule,
    ) -> None:
        """Optimizer only finds anomalies → 'No se detectaron patrones'."""
        # Seed data that would trigger DegradationDetector (anomaly type)
        # but minimal data so BaselineGenerator may not fire
        now = datetime.now(UTC)
        _seed_multiple(
            real_pulse,
            [
                # 4 similar units so DegradationDetector has baseline
                {
                    "id": "ano-wu-1",
                    "model": "gpt-4",
                    "tokens_input": 100,
                    "tokens_output": 50,
                    "cost": Decimal("0.01"),
                    "created_at": (now - timedelta(hours=2)).isoformat(),
                },
                {
                    "id": "ano-wu-2",
                    "model": "gpt-4",
                    "tokens_input": 110,
                    "tokens_output": 55,
                    "cost": Decimal("0.011"),
                    "created_at": (now - timedelta(hours=2)).isoformat(),
                },
                {
                    "id": "ano-wu-3",
                    "model": "gpt-4",
                    "tokens_input": 105,
                    "tokens_output": 52,
                    "cost": Decimal("0.0105"),
                    "created_at": (now - timedelta(hours=2)).isoformat(),
                },
                {
                    "id": "ano-wu-4",
                    "model": "gpt-4",
                    "tokens_input": 5000,
                    "tokens_output": 2500,
                    "cost": Decimal("0.50"),
                    "created_at": (now - timedelta(hours=2)).isoformat(),
                },
            ],
        )
        ctx = Context(services={"pulse.measurements": real_pulse.list})
        optimizer = OptimizerModule({})
        await optimizer.start(ctx)

        registry = ServiceRegistry(optimizer=optimizer, pulse=real_pulse)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        # The 5000-token outlier may trigger DegradationDetector (anomaly)
        # or just pass through. If BaselineGenerator fires it's type=pattern.
        # If only anomalies → no patterns.
        if "error" in result:
            # Could also be no patterns at all if detectors don't fire
            pass
        else:
            assert "summary" in result

    async def test_no_hypotheses_at_all(
        self,
        optimizer_no_pulse: OptimizerModule,
    ) -> None:
        """Optimizer with no data → no hypotheses → no patterns."""
        registry = ServiceRegistry(optimizer=optimizer_no_pulse)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        assert "error" not in result
        assert "No se detectaron patrones" in result["summary"]
        assert result["confidence"] == 0.0
        assert result["suggested_action"] is None
        assert result["data_freshness"] == 0


class TestInsightsIntegrationPulseAbsent:
    """Pulse is optional — confidence degrades when absent."""

    async def test_confidence_without_pulse(
        self,
        optimizer_with_pulse: OptimizerModule,
    ) -> None:
        """Pulse not in registry → pulse_factor = 0.5."""
        registry = ServiceRegistry(optimizer=optimizer_with_pulse)  # no pulse
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        assert "error" not in result
        # Evidence should NOT include 'Sistema de rendimiento'
        sources = [e["source"] for e in result["evidence"]]
        assert "Sistema de rendimiento" not in sources
        assert len(sources) == 1
        assert sources[0] == "Sistema de optimización"

    async def test_evidence_no_pulse(
        self,
        optimizer_with_pulse: OptimizerModule,
    ) -> None:
        """No Pulse → only Optimizer evidence."""
        registry = ServiceRegistry(optimizer=optimizer_with_pulse)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        assert len(result["evidence"]) == 1
        assert result["evidence"][0]["source"] == "Sistema de optimización"


class TestInsightsIntegrationOptimizerAbsent:
    """Optimizer is required — error when absent."""

    async def test_no_optimizer(self) -> None:
        """Optimizer=None → ERR_DEPENDENCY_UNAVAILABLE."""
        registry = ServiceRegistry()  # everything is None
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_DEPENDENCY_UNAVAILABLE"
        assert "suggested_action" not in result

    async def test_optimizer_no_services_attr(self) -> None:
        """Optimizer without 'services' attribute → error."""
        registry = ServiceRegistry(optimizer=object())
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_DEPENDENCY_UNAVAILABLE"


class TestInsightsIntegrationConfidence:
    """Confidence formula: hypothesis_avg × pulse_factor."""

    async def test_confidence_formula_with_pulse(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """With Pulse → pulse_factor = 1.0."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        # Confidence = avg(pattern_hypotheses.confidence) * 1.0
        # BaselineGenerator produces confidence based on data
        # We don't know the exact value but it must be > 0
        assert result["confidence"] > 0.0
        assert result["confidence"] <= 1.0

    async def test_confidence_zero_when_no_patterns(
        self,
        optimizer_no_pulse: OptimizerModule,
    ) -> None:
        """No patterns → confidence = 0.0."""
        registry = ServiceRegistry(optimizer=optimizer_no_pulse)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()

        assert result["confidence"] == 0.0


class TestInsightsIntegrationFreshnessAndAction:
    """Invariant checks on data_freshness and suggested_action."""

    async def test_data_freshness_always_zero(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """data_freshness is always 0 (live query, no cache)."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()
        assert result["data_freshness"] == 0

    async def test_suggested_action_always_none(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """suggested_action is always None (pure query tool)."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()
        assert result["suggested_action"] is None

    async def test_without_pulse_suggested_action_none(
        self,
        optimizer_with_pulse: OptimizerModule,
    ) -> None:
        """Even degraded, suggested_action stays None."""
        registry = ServiceRegistry(optimizer=optimizer_with_pulse)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.insights()
        assert result["suggested_action"] is None


class TestInsightsIntegrationP6Compliance:
    """P6: No internal structure or module names exposed."""

    async def test_no_internal_evidence_dict(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Response never contains internal evidence dict with stats."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        response_str = str(result)
        # Internal evidence keys should NOT appear
        assert "mean" not in response_str
        assert "std" not in response_str
        assert "min" not in response_str
        assert "max" not in response_str
        assert "z_score" not in response_str
        assert "iqr" not in response_str
        assert "hour_histogram" not in response_str

    async def test_no_module_names(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """No module/internal names in response."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        response_str = str(result)
        assert "OptimizerModule" not in response_str
        assert "PulseModule" not in response_str
        assert "BaselineGenerator" not in response_str
        assert "optimizer.hypotheses" not in response_str
        assert "pulse.measurements" not in response_str

    async def test_sources_are_functional_labels(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Evidence sources use functional labels, not module names."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.insights()

        for entry in result["evidence"]:
            assert "optimizer" not in entry["source"].lower()
            assert "sistema" in entry["source"].lower()
