"""Integration tests for ApochCoordinator.logs() with REAL components.

Uses:
  - REAL VisionModule (from apoch.modules.vision.module)
  - REAL LogRecord (from apoch.modules.vision.models)
  - REAL Module/Context from apoch.core.module

Minimal fakes:
  - None for Vision — VisionModule runs fully real with in-memory ring buffer.
  - The ring buffer is seeded via REAL VisionModule.log() calls.
  - No mocked methods on VisionModule at all.

Every log entry is generated by REAL VisionModule.log() and retrieved
via REAL VisionModule.recent() through the coordinator pipeline.
"""

from __future__ import annotations

from datetime import datetime

import pytest

from apoch.core.module import Context
from apoch.modules.vision.module import VisionModule
from apoch.public_api.coordinator import ApochCoordinator
from apoch.public_api.registry import ServiceRegistry

# ---------------------------------------------------------------------------
# Fixtures: REAL VisionModule
# ---------------------------------------------------------------------------


@pytest.fixture
def empty_context() -> Context:
    """Empty Context — no cross-module services."""
    return Context()


@pytest.fixture
def real_vision(empty_context: Context, tmp_path: str) -> VisionModule:
    """A REAL VisionModule, started and ready.

    Uses tmp_path for the log directory so file logging works but leaves
    no traces after the test.  The in-memory ring buffer is the primary
    data source for tests.
    """
    mod = VisionModule({"log_dir": str(tmp_path), "buffer_size": 200})
    import asyncio

    asyncio.run(mod.start(empty_context))
    return mod


def _seed_logs(
    vision: VisionModule,
    *,
    count: int = 5,
    base_message: str = "entry",
    base_module: str = "core",
) -> None:
    """Seed *count* log entries via REAL VisionModule.log().

    Entries are spread across different levels and modules to enable
    filter testing.
    """
    for i in range(count):
        level = "INFO"
        module = base_module
        message = f"{base_message}-{i}"
        if i % 3 == 1:
            level = "ERROR"
        elif i % 3 == 2:
            level = "WARN"
        if i >= 3:
            module = "pulse"
        vision.log(level, message, module=module)


@pytest.fixture
def vision_with_logs(real_vision: VisionModule) -> VisionModule:
    """VisionModule with 5 seeded log entries."""
    _seed_logs(real_vision, count=5)
    return real_vision


@pytest.fixture
def vision_empty(real_vision: VisionModule) -> VisionModule:
    """VisionModule with no log entries (empty buffer)."""
    return real_vision


@pytest.fixture
def full_registry(vision_with_logs: VisionModule) -> ServiceRegistry:
    """Registry with REAL VisionModule that has data."""
    return ServiceRegistry(vision=vision_with_logs)


@pytest.fixture
def empty_registry(vision_empty: VisionModule) -> ServiceRegistry:
    """Registry with REAL VisionModule with no data."""
    return ServiceRegistry(vision=vision_empty)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestLogsIntegrationHappyPath:
    """REAL Vision with real log data — full pipeline."""

    async def test_logs_return_real_entries(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Seed 5 entries → logs() returns summary with '5 entradas'."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        assert "error" not in result
        assert "5 entradas" in result["summary"]
        assert result["suggested_action"] is None
        assert result["api_version"] == "1.0"
        assert result["data_freshness"] == 0
        assert result["metadata"] == {}

    async def test_explanation_format(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Each line: [timestamp] LEVEL [module] — message."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        lines = result["explanation"].split("\n")
        assert len(lines) == 5
        for line in lines:
            assert line.startswith("[")
            assert " — " in line

    async def test_confidence_with_data(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Vision has data → confidence = 1.0."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()
        assert result["confidence"] == 1.0

    async def test_evidence_source(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Evidence uses 'Sistema de monitoreo' functional label."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        assert len(result["evidence"]) == 1
        ev = result["evidence"][0]
        assert ev["source"] == "Sistema de monitoreo"
        assert ev["confidence"] == 0.8
        assert "based_on" in ev

    async def test_response_contract(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """All ToolResponse fields present."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        assert set(result.keys()) == {
            "api_version",
            "summary",
            "explanation",
            "evidence",
            "suggested_action",
            "confidence",
            "generated_at",
            "data_freshness",
            "metadata",
        }

    async def test_generated_at_is_iso(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """generated_at is parseable ISO 8601."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        dt = datetime.fromisoformat(result["generated_at"])
        assert dt.tzinfo is not None

    async def test_no_context_or_pid_in_output(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Output NEVER contains context, pid, or LogRecord internals."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        explanation = result["explanation"]
        assert "context" not in explanation
        assert "pid" not in explanation
        assert "LogRecord" not in explanation
        # The seeded entries have no module=None case, so all lines show [module]
        assert "[" in explanation

    async def test_idempotent_call(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Consecutive calls return same structure (diff generated_at)."""
        coordinator = ApochCoordinator(full_registry)
        r1 = await coordinator.logs()
        r2 = await coordinator.logs()

        assert r1["summary"] == r2["summary"]
        assert len(r1["evidence"]) == len(r2["evidence"])
        assert r1["confidence"] == r2["confidence"]
        assert r1["generated_at"] != r2["generated_at"]


class TestLogsIntegrationFilters:
    """REAL Vision — parameter filter verification."""

    async def test_filter_by_nivel(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """nivel='WARN' → only WARN entries."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(nivel="WARN")

        lines = result["explanation"].split("\n")
        assert all("WARN" in line for line in lines)
        assert len(lines) > 0

    async def test_filter_by_nivel_case_insensitive(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """nivel='warn' → case-insensitive match."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(nivel="warn")

        lines = result["explanation"].split("\n")
        assert all("WARN" in line for line in lines)

    async def test_filter_by_modulo(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """modulo='core' → only core entries (applied in-memory)."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(modulo="core")

        lines = result["explanation"].split("\n")
        assert all("[core]" in line for line in lines)

    async def test_filter_by_modulo_and_limite(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """modulo + limite → limite applies AFTER module filter."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(modulo="pulse", limite=1)

        lines = result["explanation"].split("\n")
        assert len(lines) == 1
        assert "[pulse]" in lines[0]

    async def test_limite_caps_output(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """limite=2 → only 2 entries returned."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(limite=2)

        lines = result["explanation"].split("\n")
        assert len(lines) == 2

    async def test_no_matching_module(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """modulo='nonexistent' → 'No hay entradas' + confidence 0.3."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(modulo="nonexistent")

        assert result["confidence"] == 0.3
        assert "No hay entradas de log" in result["summary"]
        assert result["suggested_action"] is None


class TestLogsIntegrationNoData:
    """Vision with empty buffer."""

    async def test_empty_buffer(
        self,
        empty_registry: ServiceRegistry,
    ) -> None:
        """No logs → confidence 0.3 and no-data message."""
        coordinator = ApochCoordinator(empty_registry)
        result = await coordinator.logs()

        assert result["confidence"] == 0.3
        assert "No hay entradas de log" in result["summary"]
        assert result["suggested_action"] is None
        assert result["data_freshness"] == 0


class TestLogsIntegrationVisionAbsent:
    """Vision is required — error when absent."""

    async def test_no_vision(self) -> None:
        """Vision=None → ERR_DEPENDENCY_UNAVAILABLE."""
        registry = ServiceRegistry()  # vision is None by default
        coordinator = ApochCoordinator(registry)
        result = await coordinator.logs()

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_DEPENDENCY_UNAVAILABLE"
        assert "suggested_action" not in result

    async def test_vision_no_recent_attr(self) -> None:
        """Vision without 'recent' → error."""
        registry = ServiceRegistry(vision=object())
        coordinator = ApochCoordinator(registry)
        result = await coordinator.logs()

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_DEPENDENCY_UNAVAILABLE"


class TestLogsIntegrationInvalidParams:
    """Validation of nivel and limite parameters."""

    async def test_invalid_nivel(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """nivel='DEBUG' → ERR_INVALID_ARGUMENT (DEBUG not in valid set)."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(nivel="DEBUG")

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_INVALID_ARGUMENT"

    async def test_invalid_nivel_lowercase(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """nivel='debug' → ERR_INVALID_ARGUMENT."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(nivel="debug")

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_INVALID_ARGUMENT"

    async def test_limite_zero(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """limite=0 → ERR_INVALID_ARGUMENT."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(limite=0)

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_INVALID_ARGUMENT"

    async def test_limite_negative(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """limite=-5 → ERR_INVALID_ARGUMENT."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs(limite=-5)

        assert result.get("ok") is False
        assert result["error"]["code"] == "ERR_INVALID_ARGUMENT"


class TestLogsIntegrationP6Compliance:
    """P6: No internal structure or raw data exposed."""

    async def test_no_context_dict_in_explanation(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """The context dict from LogRecord never appears in explanation."""
        # Seed an entry with rich context data
        coordinator = ApochCoordinator(full_registry)
        _seed_logs(coordinator._services.vision, count=1, base_message="ctx-test")

        result = await coordinator.logs()
        explanation = result["explanation"]

        # LogRecord.context is never serialized
        assert "context" not in explanation.lower()
        assert "retry_count" not in explanation
        assert "{" not in explanation

    async def test_no_module_names_in_sources(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Evidence source is 'Sistema de monitoreo', not 'VisionModule'."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        for entry in result["evidence"]:
            assert "vision" not in entry["source"].lower()
            assert "sistema" in entry["source"].lower()

    async def test_explanation_has_no_raw_python(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """Explanation contains formatted strings, not repr()."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()

        explanation = result["explanation"]
        assert "LogRecord" not in explanation
        assert "<" not in explanation  # no repr output
        assert "object at" not in explanation


class TestLogsIntegrationSuggestedAction:
    """suggested_action invariant."""

    async def test_suggested_action_with_data(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """With data → suggested_action is None."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()
        assert result["suggested_action"] is None

    async def test_suggested_action_empty(
        self,
        empty_registry: ServiceRegistry,
    ) -> None:
        """No data → suggested_action is None."""
        coordinator = ApochCoordinator(empty_registry)
        result = await coordinator.logs()
        assert result["suggested_action"] is None

    async def test_suggested_action_error(
        self,
    ) -> None:
        """Vision absent → suggested_action not in error envelope."""
        coordinator = ApochCoordinator(ServiceRegistry())
        result = await coordinator.logs()
        assert "suggested_action" not in result


class TestLogsIntegrationDataFreshness:
    """data_freshness invariant."""

    async def test_data_freshness_with_data(
        self,
        full_registry: ServiceRegistry,
    ) -> None:
        """With data → data_freshness = 0."""
        coordinator = ApochCoordinator(full_registry)
        result = await coordinator.logs()
        assert result["data_freshness"] == 0

    async def test_data_freshness_empty(
        self,
        empty_registry: ServiceRegistry,
    ) -> None:
        """No data → data_freshness = 0."""
        coordinator = ApochCoordinator(empty_registry)
        result = await coordinator.logs()
        assert result["data_freshness"] == 0


class TestLogsIntegrationDynamicBehavior:
    """Dynamic: new logs appear on subsequent calls."""

    async def test_new_logs_appear_on_next_call(
        self,
        real_vision: VisionModule,
    ) -> None:
        """Log a new entry → next logs() call includes it."""
        registry = ServiceRegistry(vision=real_vision)
        coordinator = ApochCoordinator(registry)

        # Initially empty
        r1 = await coordinator.logs()
        assert r1["confidence"] == 0.3

        # Seed a log entry
        real_vision.log("INFO", "new dynamic entry", module="test")

        # Now it should appear
        r2 = await coordinator.logs()
        assert r2["confidence"] == 1.0
        assert "1 entrada" in r2["summary"] or "1 entradas" in r2["summary"]
        assert "new dynamic entry" in r2["explanation"]

    async def test_logs_newest_first(
        self,
        real_vision: VisionModule,
    ) -> None:
        """Entries are returned newest-first (Vision.recent() reverses buffer)."""
        real_vision.log("INFO", "first entry", module="test")
        real_vision.log("INFO", "second entry", module="test")

        registry = ServiceRegistry(vision=real_vision)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.logs()

        lines = result["explanation"].split("\n")
        # Newest first → "second entry" should be first
        assert "second entry" in lines[0]
        assert "first entry" in lines[1]

    async def test_buffer_size_respected(
        self,
        empty_context: Context,
        tmp_path: str,
    ) -> None:
        """Buffer fills → older entries dropped."""
        vision = VisionModule({"log_dir": str(tmp_path), "buffer_size": 3})
        await vision.start(empty_context)

        vision.log("INFO", "entry-1", module="test")
        vision.log("INFO", "entry-2", module="test")
        vision.log("INFO", "entry-3", module="test")
        vision.log("INFO", "entry-4", module="test")  # entry-1 should be evicted

        registry = ServiceRegistry(vision=vision)
        coordinator = ApochCoordinator(registry)
        result = await coordinator.logs()

        assert "entry-1" not in result["explanation"]
        assert "entry-4" in result["explanation"]
        assert "3 entradas" in result["summary"]
